@startuml
participant Actor
Actor -> SubscriptionSelectionController$1 : handle
activate SubscriptionSelectionController$1
create PaymentSelectionView
SubscriptionSelectionController$1 -> PaymentSelectionView : new
activate PaymentSelectionView
PaymentSelectionView -> PaymentSelectionView : initComponents
activate PaymentSelectionView
PaymentSelectionView -> UpperBar : setForNoLogged
activate UpperBar
UpperBar --> PaymentSelectionView
deactivate UpperBar
PaymentSelectionView --> PaymentSelectionView
deactivate PaymentSelectionView
PaymentSelectionView --> SubscriptionSelectionController$1
deactivate PaymentSelectionView
create PaymentSelectionController
SubscriptionSelectionController$1 -> PaymentSelectionController : new
activate PaymentSelectionController
PaymentSelectionController -> PaymentSelectionController : initComponents
activate PaymentSelectionController
PaymentSelectionController --> PaymentSelectionController
deactivate PaymentSelectionController
PaymentSelectionController --> SubscriptionSelectionController$1
deactivate PaymentSelectionController
return
@enduml